repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.404
    hooks:
      - id: pyright

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/bufbuild/buf
    rev: v1.60.0
    hooks:
      - id: buf-lint
        exclude: \.venv/
      - id: buf-format
        exclude: \.venv/

  - repo: https://github.com/open-policy-agent/regal
    rev: v0.37.0
    hooks:
      - id: regal-lint

  - repo: https://github.com/anderseknert/pre-commit-opa
    rev: v1.5.1
    hooks:
    - id: opa-fmt
      args: [--write]