"use client";

import {
	AlertTriangle,
	ArrowLeft,
	BookOpen,
	BrainCircuit,
	Code2,
	FileText,
	Info,
	Quote,
	Scale,
} from "lucide-react";
import { useState } from "react";
import { ConstraintIcon } from "@/components/obligations/constraint-icon";
import { ConstraintVisualizer } from "@/components/obligations/constraint-visualizer";
import { EnforcementBadge } from "@/components/obligations/enforcement-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { cn } from "@/lib/utils";
import type { Obligation } from "@/types/obligation";

interface ExtractionResultsProps {
	obligations: Obligation[];
	onReset: () => void;
}

export function ExtractionResults({
	obligations,
	onReset,
}: ExtractionResultsProps) {
	const [selectedIndex, setSelectedIndex] = useState(0);

	if (!obligations || obligations.length === 0) {
		return (
			<div className="flex flex-col items-center justify-center h-96 space-y-4 animate-in fade-in">
				<div className="h-16 w-16 rounded-full bg-muted flex items-center justify-center">
					<Info className="h-8 w-8 text-muted-foreground" />
				</div>
				<h3 className="text-xl font-semibold">No Obligations Found</h3>
				<p className="text-muted-foreground">
					The AI pipeline did not extract any actionable rules.
				</p>
				<Button onClick={onReset} variant="outline" className="mt-4">
					<ArrowLeft className="mr-2 h-4 w-4" /> Back to Dashboard
				</Button>
			</div>
		);
	}

	const selectedOb = obligations[selectedIndex];

	return (
		<div className="flex flex-col h-[calc(100vh-8rem)] animate-in fade-in duration-500">
			{/* Header */}
			<div className="flex items-center justify-between pb-6 shrink-0">
				<div>
					<h2 className="text-2xl font-bold tracking-tight text-foreground flex items-center gap-2">
						<BrainCircuit className="h-6 w-6 text-indigo-500" />
						Extraction Results
					</h2>
					<p className="text-sm text-muted-foreground mt-1">
						Review the policies generated by the reasoning engine.
					</p>
				</div>
				<Button onClick={onReset} variant="secondary" size="sm">
					<ArrowLeft className="mr-2 h-4 w-4" />
					Process Another
				</Button>
			</div>

			{/* 2-Column Layout */}
			<div className="grid grid-cols-1 lg:grid-cols-3 gap-6 flex-1 min-h-0">
				{/* LEFT COLUMN: The "What" (List) */}
				<Card className="lg:col-span-1 flex flex-col border-border/50 overflow-hidden bg-card/50">
					<div className="p-4 border-b border-border/50 bg-muted/20 shrink-0 flex justify-between items-center">
						<h3 className="font-semibold text-sm">Generated Policies</h3>
						<Badge variant="secondary" className="font-mono text-xs">
							{obligations.length} total
						</Badge>
					</div>

					<ScrollArea className="flex-1">
						<div className="p-3 space-y-3">
							{obligations.map((ob, idx) => {
								const isSelected = idx === selectedIndex;
								// Detect poison pill override for UI warning
								const hasSystemOverride = ob.description.includes("[SYSTEM:");

								return (
									<button
										key={ob.id}
										onClick={() => setSelectedIndex(idx)}
										className={cn(
											"w-full text-left p-4 rounded-xl border transition-all duration-200 focus:outline-none",
											isSelected
												? "bg-indigo-500/10 border-indigo-500/50 shadow-sm"
												: "bg-background border-border/50 hover:border-border hover:bg-muted/30",
											hasSystemOverride && !isSelected && "border-amber-500/30",
											hasSystemOverride &&
												isSelected &&
												"border-amber-500 bg-amber-500/10",
										)}
									>
										<div className="flex items-start justify-between mb-2 gap-2">
											<div className="flex items-center gap-2 overflow-hidden">
												<ConstraintIcon obligation={ob} className="shrink-0" />
												<span className="font-semibold text-sm truncate text-foreground">
													{ob.title}
												</span>
											</div>
											<EnforcementBadge
												level={ob.enforcement_level}
												showIcon={false}
												className="shrink-0 scale-90 origin-top-right"
											/>
										</div>

										{/* Target Scope Summary */}
										<div className="flex flex-wrap gap-1.5 mt-3">
											{Object.entries(ob.target.match_tags || {}).map(
												([k, v]) => (
													<Badge
														key={k}
														variant="outline"
														className="text-[10px] px-1.5 py-0 bg-background/50 text-muted-foreground font-mono"
													>
														{k}:{v}
													</Badge>
												),
											)}
											{(!ob.target.match_tags ||
												Object.keys(ob.target.match_tags).length === 0) && (
												<span className="text-[10px] text-muted-foreground italic">
													Global Scope
												</span>
											)}
										</div>
									</button>
								);
							})}
						</div>
					</ScrollArea>
				</Card>

				{/* RIGHT COLUMN: The "Why" (Details & Provenance) */}
				<Card className="lg:col-span-2 flex flex-col border-border/50 overflow-hidden shadow-md">
					<Tabs defaultValue="evidence" className="flex flex-col h-full">
						<div className="px-6 pt-4 pb-0 border-b border-border/50 bg-muted/10 shrink-0">
							<TabsList className="bg-transparent h-auto p-0 gap-6">
								<TabsTrigger
									value="evidence"
									className="data-[state=active]:bg-transparent data-[state=active]:shadow-none data-[state=active]:border-b-2 data-[state=active]:border-indigo-500 rounded-none pb-3 pt-2 px-0"
								>
									<Scale className="h-4 w-4 mr-2" />
									Evidence & Rationale
								</TabsTrigger>
								<TabsTrigger
									value="code"
									className="data-[state=active]:bg-transparent data-[state=active]:shadow-none data-[state=active]:border-b-2 data-[state=active]:border-indigo-500 rounded-none pb-3 pt-2 px-0"
								>
									<Code2 className="h-4 w-4 mr-2" />
									Compiled JSON
								</TabsTrigger>
							</TabsList>
						</div>

						<ScrollArea className="flex-1 bg-card">
							<TabsContent
								value="evidence"
								className="m-0 p-6 space-y-8 focus-visible:outline-none"
							>
								{/* 1. System Overrides / Warnings */}
								{selectedOb.description.includes("[SYSTEM:") && (
									<div className="flex gap-3 p-4 rounded-lg bg-amber-500/10 border border-amber-500/30 text-amber-500">
										<AlertTriangle className="h-5 w-5 shrink-0 mt-0.5" />
										<div className="space-y-1">
											<h4 className="font-semibold text-sm">
												System Safety Override Triggered
											</h4>
											<p className="text-xs text-amber-500/80 leading-relaxed">
												The extracted logic mandated immediate data deletion
												(0-day retention). To prevent accidental data loss, the
												pipeline auto-corrected the duration to a safe default
												and downgraded enforcement to AUDIT_ONLY.
											</p>
										</div>
									</div>
								)}

								{/* 2. The Extracted Constraint (Visualized) */}
								<div className="space-y-4">
									<h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-2">
										<BrainCircuit className="h-4 w-4" />
										Technical Configuration
									</h3>
									<div className="p-5 rounded-xl border bg-muted/5">
										<ConstraintVisualizer obligation={selectedOb} />
									</div>
								</div>

								<Separator />

								{/* 3. Provenance & AI Rationale */}
								<div className="space-y-4">
									<h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-2">
										<BookOpen className="h-4 w-4" />
										AI Reasoning & Provenance
									</h3>

									<div className="grid gap-4">
										{/* Context Box */}
										<div className="flex items-center gap-4 text-sm text-muted-foreground p-3 rounded-lg bg-muted/20 border">
											<FileText className="h-4 w-4 shrink-0" />
											<div className="flex flex-col">
												<span className="font-medium text-foreground">
													Source: {selectedOb.provenance.source_id}
												</span>
												<span className="text-xs">
													{selectedOb.provenance.document_type} • Section:{" "}
													{selectedOb.provenance.section_reference || "Unknown"}
												</span>
											</div>
										</div>

										{/* Rationale Quote Box */}
										<div className="relative p-5 rounded-xl border border-indigo-500/20 bg-indigo-500/5">
											<Quote className="absolute top-4 left-4 h-6 w-6 text-indigo-500/20 rotate-180" />
											<div className="pl-8">
												<p className="text-sm text-foreground/90 leading-relaxed font-medium">
													{parseRationale(selectedOb.description)}
												</p>
											</div>
										</div>
									</div>
								</div>
							</TabsContent>

							<TabsContent
								value="code"
								className="m-0 p-6 focus-visible:outline-none"
							>
								<div className="space-y-4">
									<p className="text-sm text-muted-foreground">
										This is the exact JSON structure that will be synced to the
										Control Plane and used by the SDKs/Connectors.
									</p>
									<div className="rounded-xl border border-zinc-800 bg-[#0D0D0D] p-4 overflow-x-auto">
										<pre className="text-[11px] font-mono text-emerald-400/90 leading-relaxed">
											{JSON.stringify(selectedOb, null, 2)}
										</pre>
									</div>
								</div>
							</TabsContent>
						</ScrollArea>
					</Tabs>
				</Card>
			</div>
		</div>
	);
}

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

/**
 * Cleans up the raw description string generated by the backend deduplicator.
 * The backend formats it as: "[Found in filename] [Section X] The rationale text. [SYSTEM: ...]"
 */
function parseRationale(rawDescription: string): string {
	let cleanText = rawDescription;

	// Remove the [Found in X] prefix if present
	cleanText = cleanText.replace(/\[Found in .*?\]\s*/g, "");

	// Remove the [Section X] prefix if present
	cleanText = cleanText.replace(/\[.*?\]\s*/, "");

	// Remove the [SYSTEM: ...] warning if present (handled separately in UI)
	cleanText = cleanText.replace(/\[SYSTEM:.*?\]/g, "");

	return cleanText.trim() || rawDescription;
}
