# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ommon/v1/common.proto\x12\tcommon.v1\"\xdd\x02\n\x05\x41\x63tor\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12.\n\x04type\x18\x02 \x01(\x0e\x32\x1a.common.v1.Actor.ActorTypeR\x04type\x12\x14\n\x05roles\x18\x03 \x03(\tR\x05roles\x12@\n\nattributes\x18\x04 \x03(\x0b\x32 .common.v1.Actor.AttributesEntryR\nattributes\x1a=\n\x0f\x41ttributesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"}\n\tActorType\x12\x1a\n\x16\x41\x43TOR_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x41\x43TOR_TYPE_HUMAN\x10\x01\x12\x1e\n\x1a\x41\x43TOR_TYPE_SERVICE_ACCOUNT\x10\x02\x12\x1e\n\x1a\x41\x43TOR_TYPE_SYSTEM_INTERNAL\x10\x03\"i\n\x12ResourceIdentifier\x12\x1a\n\x08platform\x18\x01 \x01(\tR\x08platform\x12\x1a\n\x08location\x18\x02 \x01(\tR\x08location\x12\x1b\n\tnative_id\x18\x03 \x01(\tR\x08nativeId\"-\n\x03Tag\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value*\xb9\x01\n\x10SensitivityLevel\x12!\n\x1dSENSITIVITY_LEVEL_UNSPECIFIED\x10\x00\x12\x1c\n\x18SENSITIVITY_LEVEL_PUBLIC\x10\x01\x12\x1e\n\x1aSENSITIVITY_LEVEL_INTERNAL\x10\x02\x12\"\n\x1eSENSITIVITY_LEVEL_CONFIDENTIAL\x10\x03\x12 \n\x1cSENSITIVITY_LEVEL_RESTRICTED\x10\x04*\x96\x01\n\x0cRiskSeverity\x12\x1d\n\x19RISK_SEVERITY_UNSPECIFIED\x10\x00\x12\x15\n\x11RISK_SEVERITY_LOW\x10\x01\x12\x18\n\x14RISK_SEVERITY_MEDIUM\x10\x02\x12\x16\n\x12RISK_SEVERITY_HIGH\x10\x03\x12\x1e\n\x1aRISK_SEVERITY_UNACCEPTABLE\x10\x04\x42\xa9\x01\n\rcom.common.v1B\x0b\x43ommonProtoP\x01ZFgithub.com/ambyte-ai/ambyte-platform/schemas/gen/go/common/v1;commonv1\xa2\x02\x03\x43XX\xaa\x02\tCommon.V1\xca\x02\tCommon\\V1\xe2\x02\x15\x43ommon\\V1\\GPBMetadata\xea\x02\nCommon::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.common.v1B\013CommonProtoP\001ZFgithub.com/ambyte-ai/ambyte-platform/schemas/gen/go/common/v1;commonv1\242\002\003CXX\252\002\tCommon.V1\312\002\tCommon\\V1\342\002\025Common\\V1\\GPBMetadata\352\002\nCommon::V1'
  _globals['_ACTOR_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_ACTOR_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_SENSITIVITYLEVEL']._serialized_start=544
  _globals['_SENSITIVITYLEVEL']._serialized_end=729
  _globals['_RISKSEVERITY']._serialized_start=732
  _globals['_RISKSEVERITY']._serialized_end=882
  _globals['_ACTOR']._serialized_start=38
  _globals['_ACTOR']._serialized_end=387
  _globals['_ACTOR_ATTRIBUTESENTRY']._serialized_start=199
  _globals['_ACTOR_ATTRIBUTESENTRY']._serialized_end=260
  _globals['_ACTOR_ACTORTYPE']._serialized_start=262
  _globals['_ACTOR_ACTORTYPE']._serialized_end=387
  _globals['_RESOURCEIDENTIFIER']._serialized_start=389
  _globals['_RESOURCEIDENTIFIER']._serialized_end=494
  _globals['_TAG']._serialized_start=496
  _globals['_TAG']._serialized_end=541
# @@protoc_insertion_point(module_scope)
