"""Add external_id to organizations

Revision ID: 48e7671e8188
Revises: fc1c7797a558
Create Date: 2025-12-25 20:44:48.056650

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '48e7671e8188'
down_revision: str | Sequence[str] | None = 'fc1c7797a558'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('organizations', sa.Column('external_id', sa.String(), nullable=True))
	op.create_index(op.f('ix_organizations_external_id'), 'organizations', ['external_id'], unique=True)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_organizations_external_id'), table_name='organizations')
	op.drop_column('organizations', 'external_id')
	# ### end Alembic commands ###
