"""Add audit_blocks table

Revision ID: 5a05b6f99b7c
Revises: a27d1f71f00c
Create Date: 2026-01-14 12:16:36.752614

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a05b6f99b7c'
down_revision: str | Sequence[str] | None = 'a27d1f71f00c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'audit_blocks',
		sa.Column('sequence_index', sa.Integer(), nullable=False),
		sa.Column('prev_block_hash', sa.String(length=64), nullable=False),
		sa.Column('merkle_root', sa.String(length=64), nullable=False),
		sa.Column('signature', sa.String(), nullable=False),
		sa.Column('timestamp_start', sa.DateTime(), nullable=False),
		sa.Column('timestamp_end', sa.DateTime(), nullable=False),
		sa.Column('log_count', sa.Integer(), nullable=False),
		sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
		sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
		sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
		sa.Column('project_id', sa.UUID(), nullable=False),
		sa.ForeignKeyConstraint(
			['project_id'], ['projects.id'], name=op.f('fk_audit_blocks_project_id_projects'), ondelete='CASCADE'
		),
		sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_blocks')),
		sa.UniqueConstraint('project_id', 'sequence_index', name='uq_project_block_sequence'),
	)
	op.create_index(op.f('ix_audit_blocks_project_id'), 'audit_blocks', ['project_id'], unique=False)
	op.add_column('audit_logs', sa.Column('block_id', sa.UUID(), nullable=True))
	op.create_index(op.f('ix_audit_logs_block_id'), 'audit_logs', ['block_id'], unique=False)
	op.create_foreign_key(
		op.f('fk_audit_logs_block_id_audit_blocks'),
		'audit_logs',
		'audit_blocks',
		['block_id'],
		['id'],
		ondelete='RESTRICT',
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(op.f('fk_audit_logs_block_id_audit_blocks'), 'audit_logs', type_='foreignkey')
	op.drop_index(op.f('ix_audit_logs_block_id'), table_name='audit_logs')
	op.drop_column('audit_logs', 'block_id')
	op.drop_index(op.f('ix_audit_blocks_project_id'), table_name='audit_blocks')
	op.drop_table('audit_blocks')
	# ### end Alembic commands ###
