"""add triggered_by to lineage_runs

Revision ID: 9ecf16061e87
Revises: 5a05b6f99b7c
Create Date: 2026-03-27 16:45:23.791585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecf16061e87'
down_revision: Union[str, Sequence[str], None] = '5a05b6f99b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lineage_runs', sa.Column('triggered_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lineage_runs', 'triggered_by')
    # ### end Alembic commands ###
