"""Add entry_hash to audit logs

Revision ID: a27d1f71f00c
Revises: 595b84699f76
Create Date: 2026-01-11 11:13:12.177597

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a27d1f71f00c'
down_revision: str | Sequence[str] | None = '595b84699f76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('audit_logs', sa.Column('entry_hash', sa.String(length=64), server_default='', nullable=False))
	# ### end Alembic commands ###

	# Optional: We could drop the server_default here if we want to enforce application-level provision,
	# but keeping it empty string is safe for now. TODO


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('audit_logs', 'entry_hash')
	# ### end Alembic commands ###
