"""init_schema

Revision ID: f86c9f5d3c15
Revises: 
Create Date: 2025-12-16 17:15:14.895099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f86c9f5d3c15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('projects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_table('api_keys',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_api_keys_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_project_id'), 'api_keys', ['project_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('resource_urn', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audit_logs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_urn'), 'audit_logs', ['resource_urn'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_project_time_decision', 'audit_logs', ['project_id', 'timestamp', 'decision'], unique=False)
    op.create_table('lineage_runs',
    sa.Column('external_run_id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_lineage_runs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineage_runs'))
    )
    op.create_index(op.f('ix_lineage_runs_external_run_id'), 'lineage_runs', ['external_run_id'], unique=False)
    op.create_index(op.f('ix_lineage_runs_project_id'), 'lineage_runs', ['project_id'], unique=False)
    op.create_table('obligations',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('enforcement_level', sa.String(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_obligations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obligations'))
    )
    op.create_index('ix_obligations_definition', 'obligations', ['definition'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_obligations_project_id'), 'obligations', ['project_id'], unique=False)
    op.create_index(op.f('ix_obligations_slug'), 'obligations', ['slug'], unique=False)
    op.create_table('resources',
    sa.Column('urn', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_resources_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('project_id', 'urn', name='uq_project_resource_urn')
    )
    op.create_index(op.f('ix_resources_project_id'), 'resources', ['project_id'], unique=False)
    op.create_index(op.f('ix_resources_urn'), 'resources', ['urn'], unique=False)
    op.create_table('lineage_edges',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_urn', sa.String(), nullable=False),
    sa.Column('target_urn', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_lineage_edges_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['lineage_runs.id'], name=op.f('fk_lineage_edges_run_id_lineage_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineage_edges'))
    )
    op.create_index(op.f('ix_lineage_edges_project_id'), 'lineage_edges', ['project_id'], unique=False)
    op.create_index(op.f('ix_lineage_edges_run_id'), 'lineage_edges', ['run_id'], unique=False)
    op.create_index(op.f('ix_lineage_edges_source_urn'), 'lineage_edges', ['source_urn'], unique=False)
    op.create_index(op.f('ix_lineage_edges_target_urn'), 'lineage_edges', ['target_urn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lineage_edges_target_urn'), table_name='lineage_edges')
    op.drop_index(op.f('ix_lineage_edges_source_urn'), table_name='lineage_edges')
    op.drop_index(op.f('ix_lineage_edges_run_id'), table_name='lineage_edges')
    op.drop_index(op.f('ix_lineage_edges_project_id'), table_name='lineage_edges')
    op.drop_table('lineage_edges')
    op.drop_index(op.f('ix_resources_urn'), table_name='resources')
    op.drop_index(op.f('ix_resources_project_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_obligations_slug'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_project_id'), table_name='obligations')
    op.drop_index('ix_obligations_definition', table_name='obligations', postgresql_using='gin')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_lineage_runs_project_id'), table_name='lineage_runs')
    op.drop_index(op.f('ix_lineage_runs_external_run_id'), table_name='lineage_runs')
    op.drop_table('lineage_runs')
    op.drop_index('ix_audit_project_time_decision', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_urn'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_project_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
