"""add_obligation_unique_constraint

Revision ID: fc1c7797a558
Revises: f86c9f5d3c15
Create Date: 2025-12-19 10:29:49.412822

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fc1c7797a558'
down_revision: str | Sequence[str] | None = 'f86c9f5d3c15'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_unique_constraint('uq_project_obligation_slug', 'obligations', ['project_id', 'slug'])
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint('uq_project_obligation_slug', 'obligations', type_='unique')
	# ### end Alembic commands ###
