{# 
    Ambyte Databricks Unity Catalog Masking Function Template
    ---------------------------------------------------------
    Generates a SQL UDF to be used with 'ALTER TABLE ... ALTER COLUMN ... SET MASK'.
    
    Context Variables:
    - policy_name (str): Fully qualified name of the function (e.g. 'main.governance.mask_email').
    - input_type (str): Spark SQL data type (STRING, INT, BIGINT, TIMESTAMP, etc.).
    - allowed_groups (list[str]): List of Databricks Account Groups allowed to see raw data.
    - method (str): The masking strategy key (FULL, HASH, PARTIAL_EMAIL, etc.).
    - comment (str): Metadata/Audit string.
#}

-- Generated by Ambyte Policy Compiler
-- Method: {{ method }}
-- Type:   {{ input_type }}

CREATE OR REPLACE FUNCTION {{ policy_name }}(val {{ input_type }})
RETURNS {{ input_type }}
LANGUAGE SQL
DETERMINISTIC
{% if comment %}COMMENT '{{ comment | replace("'", "\\'") }}'{% endif %}
RETURN
  CASE
    -- 1. SAFETY VALVE: Always allow specific Admin groups (Configurable via Context)
    WHEN is_account_group_member('admin') OR is_account_group_member('metastore_admins') THEN val

    -- 2. ALLOWLIST: Grant access to authorized business groups
    {% if allowed_groups %}
    WHEN 
        {%- for group in allowed_groups -%}
        is_account_group_member('{{ group }}'){{ " OR " if not loop.last else "" }}
        {%- endfor -%}
    THEN val
    {% endif %}

    -- 3. MASKING LOGIC: Apply transformation based on type and method
    ELSE
        {%- if method == 'FULL' -%}
            {# --- REDACTION --- #}
            {%- if 'STRING' in input_type or 'VARCHAR' in input_type or 'CHAR' in input_type -%}
                '**********'
            {%- elif 'INT' in input_type or 'DECIMAL' in input_type or 'FLOAT' in input_type or 'DOUBLE' in input_type -%}
                CAST(NULL AS {{ input_type }})
            {%- elif 'DATE' in input_type -%}
                CAST('1970-01-01' AS DATE)
            {%- elif 'TIMESTAMP' in input_type -%}
                CAST('1970-01-01 00:00:00' AS TIMESTAMP)
            {%- else -%}
                CAST(NULL AS {{ input_type }})
            {%- endif -%}

        {%- elif method == 'HASH' -%}
            {# --- HASHING (SHA-256) --- #}
            {# Note: Can only apply hash if input is string-compatible, otherwise fallback to NULL #}
            {%- if 'STRING' in input_type or 'VARCHAR' in input_type -%}
                sha2(val, 256)
            {%- else -%}
                CAST(NULL AS {{ input_type }}) -- Type mismatch for hash
            {%- endif -%}

        {%- elif method == 'PARTIAL_EMAIL' -%}
            {# --- EMAIL MASKING (j****@gmail.com) --- #}
            CASE 
                WHEN val IS NULL THEN NULL 
                ELSE regexp_replace(val, '(^.).*@(.*$)', '$1****@$2') 
            END

        {%- elif method == 'PARTIAL_SSN' -%}
            {# --- SSN MASKING (***-**-1234) --- #}
            CASE 
                WHEN val IS NULL THEN NULL
                -- Assumes input is string. If numeric, convert, mask, but return NULL if strict types enforced.
                {%- if 'STRING' in input_type -%}
                ELSE concat('***-**-', right(val, 4))
                {%- else -%}
                ELSE CAST(NULL AS {{ input_type }})
                {%- endif -%}
            END

        {%- elif method == 'NOISE_INT' -%}
            {# --- DIFFERENTIAL PRIVACY (Noise) --- #}
            {# Valid only for numeric types #}
            {%- if 'INT' in input_type or 'DECIMAL' in input_type or 'FLOAT' in input_type or 'DOUBLE' in input_type -%}
                val + CAST((rand() * 10 - 5) AS {{ input_type }})
            {%- else -%}
                val -- Cannot add noise to non-numbers
            {%- endif -%}

        {%- else -%}
            {# --- DEFAULT FALLBACK --- #}
            CAST(NULL AS {{ input_type }})
        {%- endif -%}
  END;