{# 
    Ambyte Databricks Unity Catalog Row Filter Function Template
    ------------------------------------------------------------
    Generates a SQL UDF to be used with 'ALTER TABLE ... SET ROW FILTER'.
    Unlike Snowflake RAPs which use CURRENT_ROLE(), Databricks logic relies
    heavily on is_account_group_member() for RBAC.

    Context Variables:
    - policy_name (str): Fully qualified function name (e.g., 'main.governance.filter_us_data').
    - ref_column (str): Name of the column to check (e.g., 'region_code').
    - input_type (str): Type of the reference column (e.g., 'STRING').
    
    - allowed_groups (list[str]): Groups that bypass filtering (Full Access).
    - denied_groups (list[str]): Groups that are strictly blocked (Zero Trust).
    
    - value_mapping (dict[str, list[str]]): 
        Maps Column Values -> Allowed Groups. 
        e.g., {'US': ['us_team', 'global_sales'], 'EU': ['eu_team']}
        Used for Row-Level Security (RLS) logic.
        
    - comment (str): Metadata/Audit string.
#}

-- Generated by Ambyte Policy Compiler
-- Filter Target: {{ ref_column }} ({{ input_type }})

CREATE OR REPLACE FUNCTION {{ policy_name }}({{ ref_column }} {{ input_type }})
RETURNS BOOLEAN
LANGUAGE SQL
DETERMINISTIC
{% if comment %}COMMENT '{{ comment | replace("'", "\\'") }}'{% endif %}
RETURN
  -- 1. SAFETY VALVE: Always allow Platform/System Admins
  is_account_group_member('admin') OR is_account_group_member('metastore_admins')

  -- 2. EXPLICIT DENY: Block specific groups (e.g. 'contractors', 'interns')
  {% if denied_groups %}
  OR (
    NOT (
      {%- for group in denied_groups -%}
      is_account_group_member('{{ group }}'){{ " OR " if not loop.last else "" }}
      {%- endfor -%}
    )
  )
  {% endif %}

  -- 3. EXPLICIT ALLOW: Grant full visibility to Power Users (e.g. 'data_scientists')
  {% if allowed_groups %}
  OR (
      {%- for group in allowed_groups -%}
      is_account_group_member('{{ group }}'){{ " OR " if not loop.last else "" }}
      {%- endfor -%}
  )
  {% endif %}

  -- 4. ROW-LEVEL SECURITY (Attribute Mapping)
  --    Check if the user is in a group authorized for the specific value in this row.
  {% if value_mapping %}
  OR (
    CASE
      {% for col_val, groups in value_mapping.items() %}
      WHEN {{ ref_column }} = '{{ col_val }}' THEN 
          ({% for g in groups %}is_account_group_member('{{ g }}'){{ " OR " if not loop.last else "" }}{% endfor %})
      {% endfor %}
      -- If value is not in mapping, hide by default (Zero Trust)
      ELSE FALSE
    END
  )
  {% endif %}
  
  -- 5. DEFAULT BEHAVIOR
  --    If no RLS mapping is provided, and user wasn't in Allow list, 
  --    what happens? Usually FALSE (Deny).
  --    However, if ONLY denied_groups were provided, we might default TRUE for others.
  --    The Ambyte engine assumes Zero Trust unless configured otherwise.
  {% if not value_mapping and not allowed_groups %}
  -- No Allowlist or RLS logic was generated -> Block everyone else.
  OR FALSE
  {% else %}
  -- Fallthrough handled by conditions above.
  {% endif %}
  ;