{# 
    Ambyte Databricks Unity Catalog Policy Binding Template
    -------------------------------------------------------
    Generates 'ALTER TABLE' statements to attach UDFs to resources.
    
    Context Variables:
    - table_name (str): Fully qualified table name (e.g. 'main.sales.customers').
    
    - mask_bindings (list[dict]): List of masking rules to apply.
        - column (str): Name of the column (e.g. 'email').
        - function_name (str): Full UDF name (e.g. 'main.gov.mask_email').
        
    - row_filter_binding (dict | None): Optional row filter config.
        - function_name (str): Full UDF name.
        - columns (list[str]): Columns passed to the filter (e.g. ['region_id']).
#}

-- Generated by Ambyte Policy Compiler
-- Target: {{ table_name }}

{% if mask_bindings %}
-- 1. Apply Column Masks
{% for bind in mask_bindings %}
ALTER TABLE {{ table_name }} ALTER COLUMN {{ bind.column }} SET MASK {{ bind.function_name }};
{% endfor %}
{% endif %}

{% if row_filter_binding %}
-- 2. Apply Row Filter
-- Note: A table can only have ONE row filter in Unity Catalog.
-- This command replaces any existing filter on the table.
ALTER TABLE {{ table_name }} 
SET ROW FILTER {{ row_filter_binding.function_name }} ON ({{ row_filter_binding.columns | join(', ') }});
{% endif %}