{# 
    Ambyte Snowflake Row Access Policy Template
    -------------------------------------------
    Generates a Row Access Policy (RAP) to enforce Purpose Limitation and Access Control.
    Unlike Masking policies (which hide column data), RAPs filter entire rows based on context.

    Context Variables:
    - policy_name (str): Name of the policy (e.g., 'rap_sales_purpose_limit').
    - ref_column (str): The column name to bind to (usually an ID or region column). 
                        If enforcing purely on role/context regardless of data, this is a dummy hook.
    - input_type (str): Data type of ref_column (e.g., VARCHAR, NUMBER).
    
    - allowed_roles (list[str]): Roles explicitly granted access.
    - denied_roles (list[str]): Roles explicitly blocked (e.g., derived from denied_purposes).
    
    - denied_tags (list[str]): Strings to look for in the Snowflake QUERY_TAG. 
                               Used to block specific pipeline purposes (e.g., "MARKETING").
                               
    - comment (str): Metadata/Audit trail.
#}

-- Generated by Ambyte Policy Compiler
-- Type: Row Access Policy (Filter)
-- Target Column: {{ ref_column }} ({{ input_type }})

CREATE OR REPLACE ROW ACCESS POLICY {{ policy_name }}
AS ({{ ref_column }} {{ input_type }}) RETURNS BOOLEAN ->
    CASE
        -- 1. SAFETY VALVE: Platform Admins always have access for debugging/maintenance.
        --    This prevents "locking yourself out" of the table.
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SECURITYADMIN', 'SYSADMIN', 'AMBYTE_PLATFORM_ADMIN') THEN TRUE

        -- 2. PURPOSE LIMITATION (Session Tags):
        --    If the current session is tagged with a prohibited purpose (e.g., dbt setting query_tag='{"purpose": "marketing"}')
        --    we block access regardless of the user's role.
        {% if denied_tags %}
        WHEN (
            {%- for tag in denied_tags -%}
            CONTAINS(LOWER(NVL(CURRENT_SESSION(), '')), '{{ tag | lower }}')
            {%- if not loop.last %} OR {% endif -%}
            {%- endfor -%}
        ) THEN FALSE
        {% endif %}

        -- 3. EXPLICIT DENY (Blocking Roles):
        --    If the Obligation explicitly forbids specific roles (mapped from denied_purposes).
        {% if denied_roles %}
        WHEN CURRENT_ROLE() IN (
            {%- for role in denied_roles -%}
            '{{ role | upper }}'{{ ", " if not loop.last else "" }}
            {%- endfor -%}
        ) THEN FALSE
        {% endif %}

        -- 4. EXPLICIT ALLOW (Allowlist):
        --    Standard Role-Based Access Control.
        {% if allowed_roles %}
        WHEN CURRENT_ROLE() IN (
            {%- for role in allowed_roles -%}
            '{{ role | upper }}'{{ ", " if not loop.last else "" }}
            {%- endfor -%}
        ) THEN TRUE
        {% endif %}

        -- 5. ZERO TRUST DEFAULT:
        --    If you aren't an admin and aren't on the allow list, you see 0 rows.
        ELSE FALSE
    END;

{% if comment %}
COMMENT ON ROW ACCESS POLICY {{ policy_name }} IS '{{ comment | replace("'", "''") }}';
{% endif %}