{# 
    Ambyte Snowflake Masking Policy Template
    ----------------------------------------
    This template is rendered by the Policy Compiler to generate 
    'CREATE MASKING POLICY' statements.
    
    Context Variables:
    - policy_name (str): The name of the policy object (e.g. 'mask_pii_email')
    - input_type (str): Snowflake data type (STRING, NUMBER, DATE, etc.)
    - allowed_roles (list[str]): Roles that can see raw data.
    - method (str): The masking strategy (FULL, HASH, PARTIAL_EMAIL, etc.)
    - comment (str): Metadata about why this policy exists.
#}

-- Generated by Ambyte Policy Compiler
-- Method: {{ method }}
-- Type:   {{ input_type }}

CREATE OR REPLACE MASKING POLICY {{ policy_name }} AS (val {{ input_type }})
RETURNS {{ input_type }} ->
    CASE
        -- 1. Always allow Super Admins (Safety Valve)
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SECURITYADMIN', 'AMBYTE_PLATFORM_ADMIN') THEN val

        -- 2. Grant access to authorized business roles
        {% if allowed_roles %}
        WHEN CURRENT_ROLE() IN (
            {%- for role in allowed_roles -%}
            '{{ role | upper }}'{{ ", " if not loop.last else "" }}
            {%- endfor -%}
        ) THEN val
        {% endif %}

        -- 3. Apply Masking Logic for everyone else
        ELSE
            {%- if method == 'FULL' -%}
                {# Full redaction based on type #}
                {%- if input_type in ['STRING', 'VARCHAR', 'TEXT', 'CHAR'] -%}
                    '**********'
                {%- elif input_type in ['NUMBER', 'INTEGER', 'FLOAT', 'DOUBLE', 'DECIMAL'] -%}
                    NULL -- Or strict numeric flag like -1
                {%- elif 'TIMESTAMP' in input_type or input_type == 'DATE' -%}
                    '1970-01-01'::{{ input_type }}
                {%- else -%}
                    NULL
                {%- endif -%}

            {%- elif method == 'HASH' -%}
                {# Deterministic pseudonomization (SHA2-256) #}
                {# Note: Returns HEX string, so input_type must be string-compatible #}
                SHA2(CAST(val AS VARCHAR), 256)

            {%- elif method == 'PARTIAL_EMAIL' -%}
                {# e.g. j****@gmail.com #}
                CASE 
                    WHEN val IS NULL THEN NULL 
                    ELSE REGEXP_REPLACE(val, '(^.).*@(.*$)', '\\1****@\\2') 
                END

            {%- elif method == 'PARTIAL_SSN' -%}
                {# e.g. ***-**-1234 #}
                CASE 
                    WHEN val IS NULL THEN NULL
                    ELSE CONCAT('***-**-', RIGHT(TO_VARCHAR(val), 4))
                END

            {%- elif method == 'NOISE_INT' -%}
                {# Differential Privacy (Simple Implementation) - Add random noise #}
                {# CAUTION: This breaks exact aggregations #}
                val + UNIFORM(-5, 5, RANDOM())

            {%- else -%}
                {# Fallback to NULL if method is unknown or 'ROW_LEVEL_SECURITY' #}
                NULL
            {%- endif -%}
    END;

{% if comment %}
COMMENT ON MASKING POLICY {{ policy_name }} IS '{{ comment | replace("'", "''") }}';
{% endif %}