{# 
    Ambyte Snowflake Tag Binding Template
    -------------------------------------
    Attaches a Masking Policy to a Tag.
    Any column in Snowflake tagged with this tag will automatically 
    inherit the policy.

    Context Variables:
    - policy_name (str): The name of the masking policy (e.g. 'mask_email').
    - tag_name (str): The fully qualified tag name (e.g. 'governance.tags.pii_category').
#}

-- Generated by Ambyte Policy Compiler
-- Action: Bind Policy to Tag

ALTER TAG {{ tag_name }} SET MASKING POLICY {{ policy_name }};

-- Note: This applies to future tagged columns automatically.
-- Existing columns usually update immediately, but large tables may queue.